<?php

require_once dirname(__FILE__) . '/../../classes/Player.class.php';

/**
 * Test class for Player.
 * Generated by PHPUnit on 2012-01-07 at 00:13:16.
 */
class PlayerTest extends PHPUnit_Framework_TestCase {

	/**
	 * @var Player
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp() {
		$this->object = new Player(123456);
		$this->object->setAcceptAbnormal(true);
		$this->object->setTeam('AT');
		$this->object->setName('Gonzales');
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown() {
		
	}

	/**
	 * @covers {className}::{origMethodName}
	 */
	public function testGetAcceptAbnormal() {
		$this->assertEquals(true, $this->object->getAcceptAbnormal());
	}

	/**
	 * @covers {className}::{origMethodName}
	 */
	public function testSetAcceptAbnormal() {
		$this->object->setAcceptAbnormal(false);
		$this->assertEquals(false, $this->object->getAcceptAbnormal());
	
	}

	/**
	 * @covers {className}::{origMethodName}
	 */
	public function testGetTeam() {
		$this->assertEquals('AT', $this->object->getTeam());
	}

	/**
	 * @covers {className}::{origMethodName}
	 */
	public function testSetTeam() {
		$this->object->setTeam('TO');
		$this->assertEquals('TO', $this->object->getTeam());
	
	}

	/**
	 * @covers {className}::{origMethodName}
	 */
	public function testGetName() {
		$this->assertEquals('Gonzales', $this->object->getName());
	}

	/**
	 * @covers {className}::{origMethodName}
	 */
	public function testGetOffset() {
		$this->assertEquals(123456, $this->object->getOffset());
	}

	/**
	 * @covers {className}::{origMethodName}
	 */
	public function testGetLineupNumber() {
		$this->assertEquals(3, $this->object->getLineupNumber());
	}

	/**
	 * @covers {className}::{origMethodName}
	 * @todo Implement testSetLineupNumber().
	 */
	public function testSetLineupNumber() {
		$this->object->setLineupNumber(10);
		$this->assertEquals(10, $this->object->getLineupNumber());
	}

	/**
	 * @covers {className}::{origMethodName}
	 * @todo Implement testSetName().
	 */
	public function testSetName() {
		$this->object->setName('Perez');
		$this->assertEquals('Perez', $this->object->getName());
	}

	/**
	 * @covers {className}::{origMethodName}
	 * @todo Implement testGetType().
	 */
	public function testGetType() {
		$this->assertEquals(null, $this->object->getType());
	}

	/**
	 * @covers {className}::{origMethodName}
	 * @todo Implement testSetType().
	 */
	public function testSetType() {
		$this->object->setType('Pitcher');
		$this->assertEquals('Pitcher', $this->object->getType());
	}

}

?>
