<?php

require_once dirname(__FILE__) . '/../../classes/TeamROMMapper.class.php';

/**
 * Test class for TeamROMMapper.
 * Generated by PHPUnit on 2012-01-11 at 02:52:12.
 */
class TeamROMMapperTest extends PHPUnit_Framework_TestCase {

	/**
	 * @var TeamROMMapper
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp() {
		$this->object = new TeamROMMapper;
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown() {
		
	}

	/**
	 * @covers {className}::{origMethodName}
	 */
	public function testGetAllTeams() {
		
	}

}

?>
